'From Cuis 5.0 of 7 November 2016 [latest update: #3293] on 2 May 2018 at 5:36:26 pm'!
'Description Enter a word in English and find... '!
!provides: 'IA-En-Dictionary' 1 2!
SystemOrganization addCategory: #'IA-En-Dictionary'!


!classDefinition: #IEDict category: #'IA-En-Dictionary'!
Object subclass: #IEDict
	instanceVariableNames: ''
	classVariableNames: 'DictData'
	poolDictionaries: ''
	category: 'IA-En-Dictionary'!
!classDefinition: 'IEDict class' category: #'IA-En-Dictionary'!
IEDict class
	instanceVariableNames: ''!


!IEDict commentStamp: '<historical>' prior: 0!
I embody aspecialized Dictionary...!
